set -e

DATABASE_MASTER_IP=$1
DATABASE_MASTER_PORT=$2
SLAVE_USER_PASSWORD=$3

sudo mysql -v -e "CHANGE MASTER TO MASTER_HOST='${DATABASE_MASTER_IP}', MASTER_PORT=${DATABASE_MASTER_PORT}, MASTER_USER='slave_user', MASTER_PASSWORD='${SLAVE_USER_PASSWORD}', GET_MASTER_PUBLIC_KEY=1;"
sudo mysql -v -e "FLUSH PRIVILEGES;"
sudo mysql -v -e "START SLAVE;"
