- name: Register env variable
  ansible.builtin.set_fact:
    env: "{{item.env.be}}"
  loop: "{{vms}}"
  when: "private_ipv4_addresses[0] == item.private_ip"
- name: Ensures backend dir exists
  file: path=/backend/ state=directory
- name: Copy Backend Dockerfile
  ansible.builtin.copy:
    src: "."
    dest: /backend/
- name: Build backend image
  community.docker.docker_image:
    name: petclinic-backend
    source: build
    build:
      path: /backend
      args: "{{env}}"
- name: Deploy backend container
  community.docker.docker_container:
    name: petclinic-backend
    image: petclinic-backend
    ports: "{{env.BACKEND_PORT}}:{{env.BACKEND_PORT}}"
    network_mode: host
